/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AssignmentGUI.java
 *
 * Created on Dec 21, 2010, 3:05:43 PM
 */
package zangleapitest;

/**
 * @author User
 */
public class AssignmentGUI extends javax.swing.JFrame {

    private static AssignmentGUI instance;

    public static AssignmentGUI getInstance() {
        if (instance == null) {
            instance = new AssignmentGUI();
        }
        return instance;
    }

    /**
     * Creates new form AssignmentGUI
     */
    private AssignmentGUI() {
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        assignmentname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        duedate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        points = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        extracredit = new javax.swing.JLabel();
        notgraded = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        percent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Assignment Name: ");

        assignmentname.setText("Wait...");

        jLabel3.setText("Due Date:");

        duedate.setText("Wait...");

        jLabel5.setText("Points Possible:");

        points.setText("Wait...");

        jLabel7.setText("Score:");

        score.setText("Wait...");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Extra Credit:");

        jLabel4.setText("Not Graded:");

        extracredit.setText("Wait...");

        notgraded.setText("Wait...");

        jLabel6.setText("Percent:");

        percent.setText("Wait...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(score)
                                                .addGap(69, 69, 69)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(assignmentname))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(duedate))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(points)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel2))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(extracredit)
                                                                        .addComponent(notgraded)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(percent)))
                                                .addContainerGap(24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(assignmentname)
                                        .addComponent(jLabel2)
                                        .addComponent(extracredit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(duedate)
                                        .addComponent(jLabel4)
                                        .addComponent(notgraded))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(points))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(score))
                                                .addContainerGap(22, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(percent))
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1))))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setDialogTitle(String title) {
        setTitle(title);
    }

    public void set(String name, String points, String score, String duedate, double percent, boolean extracredit, boolean notgraded) {
        assignmentname.setText(name);
        this.points.setText(points);
        if (score == null) {
            this.score.setText("No score");
        } else {
            this.score.setText(score);
        }
        this.duedate.setText(duedate);

        this.percent.setText(percent + "%");

        if (extracredit == true) {
            this.extracredit.setText("Yes");
        } else {
            this.extracredit.setText("No");
        }

        if (notgraded == true) {
            this.notgraded.setText("Yes");
        } else {
            this.notgraded.setText("No");
        }
    }

    public void create() {
        instance = null;
        getInstance().initComponents();
        getInstance().setVisible(true);
        getInstance().setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel assignmentname;
    private javax.swing.JLabel duedate;
    private javax.swing.JLabel extracredit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel notgraded;
    private javax.swing.JLabel percent;
    private javax.swing.JLabel points;
    private javax.swing.JLabel score;
    // End of variables declaration
}
